algoritmo "MOD e DIV"
//DIV retorna a parte inteira da divisão
//MOD retorna o resto da divisão
var
a, b, c , d: inteiro
f, g: real
inicio

escreval("Digite o primeiro número: ")
leia(a)
escreval("Digite o segundo número: ")
leia(b)
escreval("Digite o terceiro número: ")
leia(c)
escreval("Digite o quarto número: ")
leia(d)

f <- a DIV b
escreval("A parte inteira dessa divisão é: ",f)
g <- c % d
escreval("O resto dessa divisão é: ", g)

fimalgoritmo
