algoritmo "Trabalhando com Tipos"

var
numero1,  numero2, soma, subtracao, multiplicacao: inteiro
divisao: real
inicio

escreval("N1:")
leia(numero1)
escreval("N2:")
leia(numero2)
soma <- numero1 + numero2
escreval("Soma: ",soma)
subtracao <- numero1 - numero2
escreval("Subtração: ", subtracao)
multiplicacao <- numero1 * numero2
escreval("Multiplicação: ", multiplicacao)
divisao <- numero1 / numero2
escreval("Divisão: ", divisao)

fimalgoritmo
