algoritmo "Trabalhando Tipos"

var
palavra1, palavra2, palavra3: literal
numero1, numero2, numero3: inteiro
inicio

escreval("Digite a primeira palavra:")
leia(palavra1)
escreval("Digite a segunda palavra:")
leia(palavra2)
escreval("Digite o primeiro número:")
leia(numero1)
escreval("Digite o segundo número:")
leia(numero2)
escreval("====")
palavra3 <- palavra1 + palavra2
numero3 <- numero1 + numero2
escreval(palavra3)
escreval(numero3)

fimalgoritmo
